name: Carol's 10 Cents
url: http://carol-nichols.com
description: This blog was re-released before it was ready

permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

gems:
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-redirect-from
